services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    environment:
      - RIOT_API_KEY=${RIOT_API_KEY:-}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost', 8000)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  chat-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    environment:
      - MCP_SERVER_URL=http://mcp-server:8000
    depends_on:
      mcp-server:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge