[project]
name = "rift-rewind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.42",
    "gradio>=5.47.2",
    "httpx>=0.28.1",
    "mcp[cli]>=1.14.1",
    "python-dotenv>=1.1.1",
]
